snd-soc-adi-axi-i2s-objs := axi-i2s.o
snd-soc-adi-axi-spdif-objs := axi-spdif.o
snd-soc-adv7511-hdmi-objs := adv7511_hdmi.o
snd-soc-zingsk-aic23b-objs := zingsk_aic23b.o
  
obj-$(CONFIG_SND_SOC_ADI_AXI_I2S) += snd-soc-adi-axi-i2s.o
obj-$(CONFIG_SND_SOC_ADI_AXI_SPDIF) += snd-soc-adi-axi-spdif.o

obj-$(CONFIG_SND_SOC_ADV7511_HDMI) += snd-soc-adv7511-hdmi.o
obj-$(CONFIG_SND_SOC_ZINGSK_AIC23B) += snd-soc-zingsk-aic23b.o
